### ISSUE TITLE
Problem: typing strings at graph level becomes tedious

### ISSUE THREAD

**Issue by sjmackenzie** [fractalide/fractalide#192]
Solution: 
### Actual behaviour
``` racket
   (node "clone1" ${clone})
   (node "clone2" ${clone})
   (node "not1" ${math.not})
   (node "not2" ${math.not})
   (node "and1" ${math.and})

   (edge-in "a" "clone1" "in")
   (edge "clone1" "out" 1 "not1" "in" _)
   (edge "clone1" "out" 2 "and2" "a" _)
   (edge "not1" "out" _ "and1" "a" _)
   (edge "and1" "out" _ "or" "a" _)
```
### Expected behaviour
``` racket
   (node clone1 ${clone})
   (node clone2 ${clone})
   (node not1 ${math.not})
   (node not2 ${math.not})
   (node and1 ${math.and})

   (edge-in a clone1 in)
   (edge clone1 out 1 not1 in _)
   (edge clone1 out 2 and2 a _)
   (edge not1 out _ and1 a _)
   (edge and1 out _ or a _)
```

if this is even possible

**Comment by dmichiels** [comment]
There is a "drawback" with this method : no use of variable for graph declaration...
This is a problem in `dynamic.rkt` for example.
ie:
```
(define out "clone1")
(edge out "out" 1 "not1" "in" _)
```
is not possible with the macro you proposed. It is working with the node type because there is the `${}`.
Have we to "duplicate" the graph definition with `s-edge`, `s-mesg`, ... that accept string and variable, and manage easy `edge`, `msg`, ... to accept raw identifier? 
I'm not sure it will be clearer for the end user...

**Comment by sjmackenzie** [comment]
Ah okay okay, yeah I never considered the `dynamic.rkt`. Ah well, nevermind!
