### ISSUE TITLE
Problem: Hydra doesn't like `git-export` in restricted mode

### ISSUE THREAD

**Issue by sjmackenzie** [fractalide/fractalide#198]
Hydra throws this error
```
error: access to path '/nix/store/5558737hlvr00y0qf9hjjhfardn1jq8v-racket-package.nix-src/z43snhhvlbzql1id14l8s585n3i7jj05-git-export' is forbidden in restricted mode
```

https://hydra.fractalide.com/jobset/fractalide/fractalide#tabs-errors

**Comment by clacke** [comment]
Hah! And locally it bites even faster than that:

```
[clacke@krokum:~/git/fractalide/racket2nix]$ nix-build
error: access to path '/home/clacke/git/fractalide/racket2nix/default.nix' is forbidden in restricted mode
```

**Comment by sjmackenzie** [comment]
Yeah I can't reproduce that:
```
[stewart@rivergod:~/dev/fractalide/racket2nix]$ nix-build
/nix/store/iv09jah5hrmw0fq37z73qg994bkf23k5-nix
```

**Comment by clacke** [comment]
I set restricted mode in my `nix.conf`, or, specifically, in `/etc/nixos/configuration.nix`, `nix.extraOptions`.

**Comment by clacke** [comment]
But ok, with the right encouragement it can give us some more info:

```
$ nix-build -I racket2nix=/home/clacke/git/fractalide/racket2nix -I nixpkgs=/nix/store/8wpfckjbdwhrfrfdra6gi2f69brdyz20-nixpkgs-18.09pre140705.090b7cc8f1b/nixpkgs build-racket.nix --arg package ./nix --show-trace
error: while evaluating the attribute 'src' of the derivation 'nix' at /nix/store/7vfxjlacpy9r6jhi7ank1kps2a6b2jh8-source/pkgs/stdenv/generic/make-derivation.nix:148:11:
access to path '/nix/store/hgi8kx979jvd5hfsbkc5xr6xlj8lsmsj-racket-package.nix-src/nix' is forbidden in restricted mode
```

**Comment by clacke** [comment]
I don't even remember why I'm copying the source one time extra. Should have done more granular commits, the `src` output is part of the creation of all of `build-racket.nix`.

**Comment by clacke** [comment]
Ok, removing it doesn't help, just moves the problem elsewhere.

**Comment by clacke** [comment]
Oh. I get it. I think `src` cannot point to some random place in `/nix/store` because that's not reproducible. The generated nix code looks like this (using a less confusingly-named example than nix (racket2nix) itself):

```
  _fractalide = mkRacketDerivation rec {
  name = "fractalide";
  src = /nix/store/v25hibqphkkkbcg54ng3pbmnwhy04gs2-racket-package.nix-src/fractalide;
  racketBuildInputs = [ _base _gui-lib _typed-map-lib _typed-racket-more _racket-lib _srfi-lite-lib _data-lib _syntax-color-lib _draw-lib _snip-lib _wxme-lib _pict-lib _scheme-lib _scribble-lib _string-constants-lib _option-contract-lib _2d-lib _compatibility-lib _tex-table _gui-i386-macosx _gui-x86_64-macosx _gui-ppc-macosx _gui-win32-i386 _gui-win32-x86_64 _gui-x86_64-linux-natipkg _at-exp-lib _rackunit-lib _testing-util-lib _parser-tools-lib _net-lib _sandbox-lib _errortrace-lib _source-syntax _draw-i386-macosx-2 _draw-x86_64-macosx-2 _draw-ppc-macosx-2 _draw-win32-i386-2 _draw-win32-x86_64-2 _draw-x86_64-linux-natipkg-2 _draw-x11-x86_64-linux-natipkg _draw-ttf-x86_64-linux-natipkg _scribble-text-lib _scribble-html-lib _planet-lib _typed-racket-lib _web-server-lib _db-lib _rackunit-gui _rackunit-typed _images-lib _racket-index _net-cookies-lib _unix-socket-lib _sasl-lib _class-iop-lib ];
  circularBuildInputs = [  ];
  reverseCircularBuildInputs = [  ];
  };
```

And that's just sort of hoping that that directory will be there. In practice it *will* be there, because it was just created when the .nix file was created, but it's still just "hey look at this random file I found". It probably needs to be a fixed-output derivation that might very well contain just a no-op build, but which does have a sha256.

**Comment by clacke** [comment]
So what `racket2nix` needs to do when it is given a directory path (rather than a git or http reference) is to generate a no-op fixed-output derivation for that directory.

But only if you use it as part of build-racket, not if you use it to generate a nix expression that you want to commit -- so it needs to be optional. Hm. Or actually, that can be detected -- if you're given a store path then you're inside nix. If you're given an arbitrary (non-store) path, then you're in the unrestricted world.
