### ISSUE TITLE
Problem: Hyperflow: how to layout a .fbp graph

### ISSUE THREAD

**Issue by dmichiels** [fractalide/fractalide#276]
Our goal is to be able to open any .fbp graph, the problem is then : 
- Should we manage an algorithm to have automatic layout?
- Should we allow the user to move nodes? 
  - If yes, were are we going to save coordinates information? 
      - In the bottom of .fbp file? It will make git a little crazy I think, the node will be harder to share...
      - In another file : It will be cleaner, but the layout will not be shared by all.
  - If there is no automatic layout, what to do with a graph without information? It seems automatic layout will be mandatory.

**Comment by clacke** [comment]
To summarize what we said on the call:
 - Load and save the Racket graphs we have today.
 - When loading, lay it out with e.g. graphviz `dot`.
 - Let the user move things around, but don't bother saving it anywhere (for now).

**Comment by clacke** [comment]
@sjmackenzie suggested to save manual layouts somewhere local, outside the repository. This means layouts become personal, only the logical graph is part of the project as such.

**Comment by sjmackenzie** [comment]
Probably the ideal scenario: We use a `*.rktd` file to store updated positions of nodes. If there is no `*.rktd` file in the `~/.racket/Hyperflow/nodestate/*` then default to the output generated by graphviz's `dot` program. Some identification scheme will be needed to locate the correct configuration file for each graph file. Though @clacke previous comment holds due to time constraints.

**Comment by dmichiels** [comment]
I agree with all of that, it is a good solution. I close as I have no more question for the moment on this subject.
