### ISSUE TITLE
Problem: Nix deletes the `target` folder and has to rebuild each time.

### ISSUE THREAD

**Issue by sjmackenzie** [fractalide/fractalide#41]
At every build nix deletes Rust's `target` folder, thus using nix in this way can increase build time by 20~30 seconds for larger components.

Reference: 
https://github.com/fractalide/fractalide/blob/master/build-support/buildFractalideComponent.nix
and
https://github.com/fractalide/fractalide/blob/master/build-support/buildRustPackage.nix

Is there a way to keep the `target` folder around?

**Comment by wizeman** [comment]
Hi @sjmackenzie ,

I'm not entirely sure I understand this issue, but as far as I understand it seems that what you want is to do incremental compilation, i.e., being able to only recompile the parts of a Rust project that have changed, instead of having to recompile the entire Rust project from scratch, is that correct? Because by default, if you change something in the source inputs, Nix does not reuse any of the previously compiled assets, instead it always rebuilds everything from scratch (starting with the unpack phase, then patch, build, test, install).

If what I wrote above is correct, then I think what you need is to use `nix-shell`, i.e. do something like this:

```
$ nix-shell '<nixpkgs>' --pure -A components.maths_boolean_nand
$ unpackPhase
$ cd $sourceRoot   #  (if this doesn't work, try cd *)
$ patchPhase
$ configurePhase   # this usually doesn't do anything in Rust projects
```

Now you can run the command `buildPhase` as many times as you want, and it will only rebuild the parts that have changed. In particular, the `target` folder will not be deleted by Nix in-between `buildPhase` commands.

However, please note that the working directory for these builds is a temporary directory that Nix has created (usually in `/tmp`). If you do any changes to the source files, they will not be copied automatically to this temporary directory, you have to modify these source files yourself in the temporary directory too (so that the next `buildPhase` command will pick up the changes).

Also, if you exit `nix-shell` then I think the next time you start `nix-shell`, you will have to start everything from scratch. So if you don't want to do all of this manually, you will probably have to drive `nix-shell` from a Python script or something...

I hope this helps!

**Comment by wizeman** [comment]
Oh wait, I think my memory has failed me above.

In fact, I think `nix-shell` will not create a temporary directory for you, it will just do everything in your current working directory. So in fact, you can do this in any directory you want, and if you exit `nix-shell`, then you can enter it again at any time and run `buildPhase` again!

So in fact, `nix-shell` will _not_ rebuild everything from scratch, if you don't want to. Which if I understood correctly, is exactly what you want?

**Comment by sjmackenzie** [comment]
Thanks so much for your response! Highly informative, though I'm not entirely sure it'll work:

```
[stewart@rivergod:~/dev/fractalide/fractalide]$ nix-shell --argstr debug true -A components.maths_boolean_nand

[nix-shell:~/dev/fractalide/fractalide]$ cd components/maths/boolean/nand/

[nix-shell:~/dev/fractalide/fractalide/components/maths/boolean/nand]$ echo $buildPhase
sed -i "s/name = .*/name = \"component\"/g" Cargo.toml sed -i "s@rustfbp .*@rustfbp = { path = \"/nix/store/pbsjjyd2fhlf9wgl9rcsss0c9mmksxir-rustfbp/src\" }@g" Cargo.toml cp /nix/store/jy9yjnnmlpc7bzaq5ihjqwiywrx59fw4-maths_boolean/src/contract_capnp.rs src/maths_boolean.rs; echo "Running cargo build " cargo build

[nix-shell:~/dev/fractalide/fractalide/components/maths/boolean/nand]$ buildPhase 
no Makefile, doing nothing

[nix-shell:~/dev/fractalide/fractalide/components/maths/boolean/nand]$ cargo build
   Compiling maths_boolean_nand v0.1.0 (file:///home/stewart/dev/fractalide/fractalide/components/maths/boolean/nand)
src/lib.rs:37:5: 37:34 error: couldn't read "src/maths_boolean.rs": No such file or directory (os error 2)
src/lib.rs:37     include!("maths_boolean.rs");
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Could not compile `maths_boolean_nand`.

To learn more, run the command again with --verbose.

```

It would be seriously awesome if `buildPhase` actually worked! Do you have a suspicion as to why it isn't working?

**Comment by sjmackenzie** [comment]
@wizeman would something need to be changed here: https://github.com/fractalide/fractalide/blob/master/build-support/buildFractalideComponent.nix#L88 ?

**Comment by sjmackenzie** [comment]
@wizeman (yes you correctly understood my vague question! thanks!)

**Comment by wizeman** [comment]
@sjmackenzie Try `eval $buildPhase` instead of simply `buildPhase`. That seems to fix it for me :-)

**Comment by wizeman** [comment]
Sorry, I meant `eval "$buildPhase"` (notice the quotation marks).

**Comment by sjmackenzie** [comment]
Hey okay! that did it, though it does make changes to the current working directory... I suppose as long as the developer doesn't commit those changes it'll be alright!

thanks @wizeman!
